#!/bin/bash
#PBS -q home-mccammon
#PBS -N glycans
#PBS -l nodes=1:ppn=3:gpu
#PBS -l walltime=192:00:00
#PBS -o glycans_nam_simulation-out.txt
#PBS -e glycans_nam_simulation-err.txt
#PBS -V
#PBS -M cseitz@ucsd.edu
#PBS -m abe
#PBS -A mccammon-gpu

export MODULEPATH=/projects/builder-group/jpg/modulefiles/applications:$MODULEPATH
module load browndye

RUNDIR=/home/cseitz/run

cd $RUNDIR

nam_simulation 2hty-oseltamivir-simulation.xml
